### PR TITLE
feat(plugin): Update plugin with null union support

### PR DESCRIPTION
**Pull request by vinnymac**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) **Where should I add the documentation for this?**

## PR Type
What kind of change does this PR introduce?
The GraphQL Plugin has been updated to broaden what code is considered nullable.

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Prior to these changes, the GraphQL plugin only supported decorating field properties when the type of a class property was optional.

Issue Number: N/A

## What is the new behavior?
Sometimes typescript users like to use union types that include null instead to indicate a nullable field. This change makes it possible to support nullable fields when the union includes a null type.

## Does this PR introduce a breaking change?
```
[x] Yes
[ ] No
```

Fields may now be nullable that were not before, this can be considered unexpected for the user.

## Other information

I noticed this functionality was missing while working with the NestJS GraphQL Plugin and my class properties such as `middleName: string | null;` were not being decorated as `nullable`. With this change, that can be supported.

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
This sounds promising! I'll review it shortly. In the meantime, would you like to create a PR with similar functionality in the `@nestjs/swagger` repository? https://github.com/nestjs/swagger Steps should be pretty much the same

**Comment by vinnymac** [comment]
Seems like similar functionality already exists in the swagger package. In fact, I believe a combination of the technique used in that project, and what I did here would be more appropriate. These changes improve this project more than the other, but I'll make PRs for both so we can discuss.

**Comment by vinnymac** [comment]
@kamilmysliwiec let me know if there is anything else you'd like to see added here.

Thanks

**Comment by kamilmysliwiec** [comment]
LGTM. Merged to v8.0.0 branch

**Pull request merged**
