### PR TITLE
chore(): 8.0.0 major release WIP

### PR DESCRIPTION
**Pull request by kamilmysliwiec**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

### CODE REVIEW

**Comment by kuskoman** [comment]
Could you consider calling server.start if you are going to introduce breaking change anyway (i deduce from semver)? https://github.com/nestjs/graphql/pull/1503/files
more information can be found here: https://github.com/nestjs/graphql/issues/1496
It is a small change but it would make gateway usage way easier

**Comment by viczam** [comment]
are we going to see [this](https://github.com/nestjs/graphql/pull/1432#issuecomment-800981372) with this release?

**Comment by olivierlacan** [comment]
Are there any documented breaking changes with this release? The release page is not very helpful determining this despite the major version bump. https://github.com/nestjs/graphql/releases/tag/8.0.0

**Comment by jmcdo29** [comment]
[The migration guide in the docs](https://docs.nestjs.com/migration-guide#nestjsgraphql-package)

**Comment by olivierlacan** [comment]
Thanks @jmcdo29 😃

**Pull request merged**
