### PR TITLE
add field deprecatedReason in inputType options for deprecating input…

### PR DESCRIPTION
**Pull request by Dev-cmyser**
… fields

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by Dev-cmyser** [comment]
hi i would like to add this feature in this library

pleade tag me for rewiew, thanks!

**Comment by kamilmysliwiec** [comment]
Could you add corresponding tests too?

**Review by micalevisk — APPROVED** [review]

**Comment by Dev-cmyser** [comment]
> Could you add corresponding tests too?

yes i could
At least I'll try

**Comment by Dev-cmyser** [comment]
it's hard)

**Comment by Dev-cmyser** [comment]
I'll try in some future sgain

**Pull request closed without merging**
