### PR TITLE
feat(): Apply transformSchema to autoSchemaFile

### PR DESCRIPTION
**Pull request by mattleff**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #993 

## What is the new behavior?

The `transformSchema` option is now applied when writing a `autoSchemaFile` to the filesystem.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by sgarner** [comment]
@mattleff This looks like a good change and I love that you are solving the schema sorting problem :+1:

But when applying `transformSchema` to the schema file, I think it might be good to either make this optional, or pass an argument to the `transformSchema` function so that we can customise transformation behavior depending on whether it is being applied for runtime or for file generation.

Some of us are [using `transformSchema` to enable Schema Stitching](https://github.com/nestjs/graphql/issues/76). In that case the result of `transformSchema` will be a gateway schema that combines the local schema with potentially multiple remote schemas. For my use case, I would prefer that the auto schema file only prints the local schema, and not the stitched gateway schema - which will no longer be the case with this PR.

**Comment by mattleff** [comment]
@sgarner Thanks for your feedback! I've made another PR to provide a `sortSchema` option: #997. That PR resolves my issue (#993) so I'll let @kamilmysliwiec decide if he wants this change as well.

**Comment by kamilmysliwiec** [comment]
> But when applying transformSchema to the schema file, I think it might be good to either make this optional, or pass an argument to the transformSchema function so that we can customise transformation behavior depending on whether it is being applied for runtime or for file generation.

To avoid breaking changes, I'd suggest applying `transformSchema` IF a dedicated flag (option) is enabled. :) Would you be able to align PR to such a requirement?

**Comment by mattleff** [comment]
> To avoid breaking changes, I'd suggest applying `transformSchema` IF a dedicated flag (option) is enabled. :) Would you be able to align PR to such a requirement?

Sure. Does `transformAutoFileSchema: boolean` sound right?

**Comment by kamilmysliwiec** [comment]
@mattleff I like it!

**Comment by mattleff** [comment]
@kamilmysliwiec This is ready for review again.

**Comment by kamilmysliwiec** [comment]
Looks great, thank you!

**Pull request merged**
