### PR TITLE
feat(mercurius): add plugins option

### PR DESCRIPTION
**Pull request by tugascript**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

There is no plugins option for mercurius like in apollo.

## What is the new behavior?
Adds a plugins paramenter for mercurius driver options like the one in apollo.

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by all2pie** [comment]
Thanks. Please also add it in Docs

**Comment by tugascript** [comment]
I am only adding it to the docs when it gets reviewed and published. This is an open pull request so it hasn't been applied to the main branch.

> Thanks. Please also add it in Docs

**Comment by all2pie** [comment]
@kamilmysliwiec Please review and merge this

**Comment by tugascript** [comment]
> @kamilmysliwiec Please review and merge this

Please don't tag the maintainers, I might be wrong but I think that's against the code of conduct. I'll look at improving this pull request when I'm home and I'll post it on the nestjs discord.

**Comment by all2pie** [comment]
@tugascript I need this support urgently and this pull request is open for a while without any interaction from mentioners. 

I don't think so that its an issue because its there job to merge the pull requests.

**Comment by tugascript** [comment]
> @tugascript I need this support urgently and this pull request is open for a while without any interaction from mentioners.
> 
> I don't think so that its an issue because its there job to merge the pull requests.

@all2pie you can use this for the time being https://gist.github.com/tugascript/7c7f2df8510303bfbbd6a30d1e3bc421 that's what I use

**Review by jmcdo29 — APPROVED** [review]
The code change itself looks simple enough and it looks like you've set up some extensive tests for this. I'm good to say it LGTM.

**Comment by jmcdo29** [comment]
We'll still need to wait for Kamil, but I didn't want this to sit any longer without at least _someone_ taking a look at it. While I don't use GraphQL or Mercurius at the moment it's obvious that supporting plugins is something that would be helpful.

**Comment by tugascript** [comment]
> We'll still need to wait for Kamil, but I didn't want this to sit any longer without at least _someone_ taking a look at it. While I don't use GraphQL or Mercurius at the moment it's obvious that supporting plugins is something that would be helpful.

Thanks!!! If there is any change he deems necessary I'll try to tackle  them over the weekend. The code is pretty simple, it's just a utility function that loads mercurius dependent plugins after mercurius itself.

**Comment by Tony133** [comment]
It would be a great addition in my opinion, by doing so you can use the plugins with both Mercurius and Apollo. 👍

**Review by Tony133 — APPROVED** [review]

**Comment by tugascript** [comment]
@kamilmysliwiec sorry for tagging but is there anything I need to change on this pull request. I think this feature would be super useful, specially for people to be able to easily add cache with the cache plugin.

**Review by Davide-Gheri — APPROVED** [review]
The change seems trivial and you added a bunch of tests to it, nice job!
Anyway, keep in mind that there is no "mercurius" plugin, they are just fastify plugins, so you can already use them by calling `await app.register` directly

**Comment by tugascript** [comment]
> The change seems trivial and you added a bunch of tests to it, nice job! Anyway, keep in mind that there is no "mercurius" plugin, they are just fastify plugins, so you can already use them by calling `await app.register` directly

Yeah they are fastify plugins, as I said earlier it's just an helper function to add fastify plugins that have mercurius on their dependency tree. If you add fastify plugins that depend on mercurius in the main file it will throw an error since mercurius would not be on the dependency tree yet.

**Comment by tugascript** [comment]
@kamilmysliwiec is there anything wrong with this pull request. It's just I still get messages asking me when this will be merged, should I improve anything or close this one and create a new one?

**Pull request closed without merging**
