### PR TITLE
feat(mercurius): add mercurius hooks

### PR DESCRIPTION
**Pull request by tugascript**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

There is no way to add [Mercurius Hooks](https://mercurius.dev/#/docs/hooks) into the Mercurius GraphQL Driver

## What is the new behavior?

Adds an optional object with the possible hooks that can be added to mercurius.

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Review by Tony133 — APPROVED** [review]
I think it is an interesting feature, I hope it will be added 🙌

**Comment by kamilmysliwiec** [comment]
There's a bunch of new conflicts that arised after I merged your other PR @tugascript (plugins support) 😢

**Comment by tugascript** [comment]
> There's a bunch of new conflicts that arised after I merged your other PR @tugascript (plugins support) cry

Yeah I expected that, I will rebase the other PR to this one

**Comment by kamilmysliwiec** [comment]
Note: 

image

This test should be already fixed on master

**Comment by tugascript** [comment]
> Note:
> 
> image
> 
> This test should be already fixed on master

Yeah somewhere on the rebase the tests were not copied I am rebasing everything again :')

**Comment by tugascript** [comment]
@kamilmysliwiec done rebasing could you double check if the tests are ok before merging, they seem in sink, but with rebasing twice have weird behaviour

**Pull request merged**
