### PR TITLE
For subscription resolvers we forward the instance method for filteri…

### PR DESCRIPTION
**Pull request by cosmin-petrescu**
For subscription resolvers we forward the instance method for filtering result using apollo withFilter

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #164

## What is the new behavior?

Subscription filter works.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Unluckily, you are not using `createContext()` which means that guards/interceptors etc won't be hooked.

**Comment by kamilmysliwiec** [comment]
Already fixed in 6.0.2 :)

**Comment by cosmin-petrescu** [comment]
Yes, its working. Thank you!

**Comment by ThinkontrolSY** [comment]
Can you give a use example about withFilter?

**Pull request closed without merging**
