### PR TITLE
Support using @apollo/subgraph 2.0.x

### PR DESCRIPTION
**Pull request by kdawgwilk**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features): N/A
- [x] Docs have been added / updated (for bug fixes / features): N/A

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

```
npm WARN Could not resolve dependency:
npm WARN peerOptional @apollo/subgraph@"^0.1.5 || ^0.3.0 || ^0.4.0" from @nestjs/graphql@10.0.10
npm WARN node_modules/@nestjs/graphql
npm WARN   @nestjs/graphql@"^10.0.10" from the root project
npm WARN   1 more (@nestjs/apollo)
```

## What is the new behavior?

Allows usage of `@apollo/subgraph` version `2.0.x` which supports federation v2 spec and is backwards compatible with federation v1

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by kdawgwilk** [comment]
This should help with https://github.com/nestjs/graphql/issues/2141

**Comment by stringbeans** [comment]
@kdawgwilk i think this is potentially dangerous as currently nestjs doesnt support federation 2...

**Comment by kdawgwilk** [comment]
@stringbeans there are no public api changes with the new subgraph version its fully backwards compatible so you could use the 2.0.x version and still be on federation v1

**Comment by stringbeans** [comment]
@kdawgwilk ah yes thats true! i think the problem is if people try to use federation v2 it wont work, but the dep will be supported in the peer dependencies

**Pull request merged**
