### PR TITLE
feat(type-graphql): generate schema sdl

### PR DESCRIPTION
**Pull request by marcus-sa**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: https://github.com/nestjs/graphql/issues/492

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by marcus-sa** [comment]
cc @kamilmysliwiec 
I don't know if you want unit/integration tests added as nothing else is tested except for with integration tests.
And do you want the docs updated for this?
Seems more like a rare utility that could be documented inline.

**Comment by kamilmysliwiec** [comment]
An integration test would be useful if you have some spare time :) Thanks for the contribution, I'll review shortly

**Comment by marcus-sa** [comment]
We should either bump TypeScript to 3.7.x or refactor the optional chaining operator

**Comment by kamilmysliwiec** [comment]
> We should either bump TypeScript to 3.7.x or refactor the optional chaining operator.
Totally forgot.

Either approach should be fine as long as the proper `target` is set in `tsconfig`. Feel free to decide:)

**Comment by johannesschobel** [comment]
Dear @marcus-sa , i would like to kindly ask about the status of this PR.
All the best

**Comment by kamilmysliwiec** [comment]
In 7.0.0, we no longer rely on the `type-graphql` package. I'll update the docs with a solution on how to generate schema without running an application shortly. Lets' track this here https://github.com/nestjs/docs.nestjs.com/issues/1076

**Comment by johannesschobel** [comment]
Wait @kamilmysliwiec .. does that mean, that the nestjs:7.0 version does not use type-graphql anymore? Even with the code-first approach? Oo"

**Comment by kamilmysliwiec** [comment]
Check out this article: https://trilon.io/blog/announcing-nestjs-7-whats-new#GraphQL-TypeScript @johannesschobel

**Comment by johannesschobel** [comment]
thanks a lot @kamilmysliwiec , i read and updated my application. works like charm! awesome release, congrats

**Comment by kamilmysliwiec** [comment]
Thanks @johannesschobel!

**Pull request closed without merging**
